"""
End-to-end LightGBM trainer.

Closes the gap FINAL_REPORT §6 left open: TRUST.md claims a "LightGBM
multiclass on triple-barrier labels with purged K-fold + embargo, MLflow-
tracked" pipeline, but until this module landed there was no orchestrator
that proved a real model trained end-to-end on real data. This module wires:

    OHLCV CSV
        → add_technical_features  (quant.features.technical)
        → triple_barrier_labels   (quant.labels.triple_barrier)
        → PurgedKFold split       (quant.cv.purged_kfold)
        → LightGBM per fold       (lightgbm.train)
        → out-of-fold predictions + per-fold + aggregated metrics
        → MLflow run + on-disk artifact bundle + reproducibility manifest

Public surface: `train(cfg: TrainConfig) -> dict` — same return shape as
`quant.backtest.runner.run_backtest`. Callers get the in-memory report and a
directory of artifacts on disk; ops gets the MLflow run.

Zero synthetic data is generated by this module. The unit-test smoke path
constructs real-arithmetic GBM prices in a pytest fixture (NOT here) — the
fake-data CI guard scans this file too.
"""

from __future__ import annotations

import json
import logging
from dataclasses import asdict
from pathlib import Path
from typing import Any

import lightgbm as lgb
import mlflow
import numpy as np
import polars as pl
from sklearn.metrics import (
    balanced_accuracy_score,
    log_loss,
    precision_recall_fscore_support,
    roc_auc_score,
)

from quant.backtest.reproducibility import build_manifest
from quant.config import settings
from quant.cv.purged_kfold import PurgedKFold
from quant.features.technical import FEATURE_COLUMNS, FEATURE_SET_VERSION, add_technical_features
from quant.labels.triple_barrier import TripleBarrierConfig, triple_barrier_labels
from quant.ml.config import TrainConfig, config_to_dict

log = logging.getLogger("quant.ml.trainer")

# Class space for LightGBM. The triple-barrier labeler emits {-1, 0, +1}; we
# remap to contiguous ids so multiclass logloss + AUC are well-defined.
_CLASSES: tuple[int, ...] = (-1, 0, 1)
_CLASS_TO_IDX: dict[int, int] = {c: i for i, c in enumerate(_CLASSES)}


# ----------------------------------------------------------------
# Data intake
# ----------------------------------------------------------------
def _load_ohlcv_csv(path: str | Path) -> pl.DataFrame:
    """
    Read the OHLCV CSV. Two schemas are accepted to keep the trainer usable
    against both the Kaggle Sandp500 5y snapshot ("Name" + no adj_close) and
    any prices CSV the backtest runner already consumes.
    """
    df = pl.read_csv(str(path), try_parse_dates=True)
    cols = set(df.columns)

    if "Name" in cols and "symbol" not in cols:
        df = df.rename({"Name": "symbol"})

    required_ohlcv = {"date", "symbol", "open", "high", "low", "close", "volume"}
    missing = required_ohlcv - set(df.columns)
    if missing:
        raise ValueError(f"{path}: missing OHLCV columns {sorted(missing)}")

    # The Kaggle dataset's `close` is already split-adjusted (per its docs);
    # treat it as adj_close when no explicit adj_close is present.
    if "adj_close" not in df.columns:
        df = df.with_columns(pl.col("close").cast(pl.Float64).alias("adj_close"))

    return df.with_columns(
        pl.col("date").cast(pl.Date),
        pl.col("open").cast(pl.Float64),
        pl.col("high").cast(pl.Float64),
        pl.col("low").cast(pl.Float64),
        pl.col("close").cast(pl.Float64),
        pl.col("volume").cast(pl.Int64),
        pl.col("adj_close").cast(pl.Float64),
    ).drop_nulls(subset=["date", "symbol", "adj_close"])


def _select_symbols(df: pl.DataFrame, max_symbols: int | None, seed: int) -> pl.DataFrame:
    """Cap symbol count for memory-bounded runs. Deterministic via seed."""
    if max_symbols is None:
        return df
    syms = df["symbol"].unique().sort().to_list()
    if len(syms) <= max_symbols:
        return df
    rng = np.random.default_rng(seed)
    chosen = sorted(rng.choice(syms, size=max_symbols, replace=False).tolist())
    return df.filter(pl.col("symbol").is_in(chosen))


# ----------------------------------------------------------------
# Feature + label assembly
# ----------------------------------------------------------------
def _build_dataset(
    prices: pl.DataFrame,
    cfg: TrainConfig,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, pl.DataFrame, list[str]]:
    """
    Returns (X, y, sample_end_idx, meta, feature_names).

    X: (N, F) float32 feature matrix
    y: (N,) int8 labels in {-1, 0, +1}
    sample_end_idx: (N,) int — for each sample i, the position in X where
        sample i's triple-barrier window closes. Used by PurgedKFold to drop
        train samples whose label window overlaps the validation block.
    meta: polars frame of the kept rows with [date, symbol, label, touch_date]
        — used for OOF artifact writing and manifest hashing.
    feature_names: stable column order matching X.
    """
    feats = add_technical_features(prices)

    label_cfg = TripleBarrierConfig(
        horizon=cfg.label.horizon,
        pt_sigma=cfg.label.pt_sigma,
        sl_sigma=cfg.label.sl_sigma,
        vol_window=cfg.label.vol_window,
        min_vol=cfg.label.min_vol,
    )
    labeled = triple_barrier_labels(
        prices.select("date", "symbol", "adj_close"),
        label_cfg,
    )

    # Inner-join on (date, symbol). Drop any row that:
    #   - has nulls/NaNs in any feature (warmup)
    #   - has no label (head/tail of each symbol's series)
    #   - has a touch_date that doesn't resolve into the kept index (rare)
    feature_cols: list[str] = list(FEATURE_COLUMNS)
    joined = (
        feats.select(["date", "symbol", *feature_cols])
        .join(
            labeled.select(["date", "symbol", "label", "touch_date"]),
            on=["date", "symbol"],
            how="inner",
        )
        .drop_nulls(subset=["label", "touch_date", *feature_cols])
    )

    # Reject rows where any feature is NaN/Inf — `drop_nulls` doesn't catch NaN.
    finite_mask = pl.all_horizontal([pl.col(c).is_finite() for c in feature_cols])
    joined = joined.filter(finite_mask)

    if joined.is_empty():
        raise RuntimeError("no labeled samples survived feature/label assembly — check date window")

    # Order matters for PurgedKFold: the splitter slices contiguous validation
    # blocks, and our `sample_end_idx` is positional. Sort by (date, symbol)
    # so val blocks are contiguous in time across the panel.
    joined = joined.sort(["date", "symbol"])

    # Map each sample's `touch_date` back to a positional index in the kept
    # frame. We approximate "first sample at or after touch_date" globally
    # (panel-level) — that overstates the overlap window slightly versus a
    # per-symbol mapping, which is the *safe* direction for purging.
    dates_np = np.asarray(joined["date"].to_list())
    touch_np = np.asarray(joined["touch_date"].to_list())
    sample_end_idx = np.searchsorted(dates_np, touch_np, side="left")
    sample_end_idx = np.clip(sample_end_idx, 0, len(dates_np) - 1).astype(np.int64)

    X = joined.select(feature_cols).to_numpy().astype(np.float32)
    y = joined["label"].to_numpy().astype(np.int8)
    meta = joined.select(["date", "symbol", "label", "touch_date"])

    return X, y, sample_end_idx, meta, feature_cols


# ----------------------------------------------------------------
# Per-fold training
# ----------------------------------------------------------------
def _train_one_fold(
    X_tr: np.ndarray,
    y_enc_tr: np.ndarray,
    X_va: np.ndarray,
    y_enc_va: np.ndarray,
    *,
    feature_names: list[str],
    cfg: TrainConfig,
) -> tuple[lgb.Booster, np.ndarray]:
    """Train one LightGBM booster with early stopping on the val fold."""
    params = dict(cfg.model.params)
    # `n_estimators` is a sklearn-API alias; lgb.train uses num_boost_round.
    params.pop("n_estimators", None)
    params["num_class"] = len(_CLASSES)

    tr_set = lgb.Dataset(X_tr, label=y_enc_tr, feature_name=feature_names, free_raw_data=False)
    va_set = lgb.Dataset(
        X_va,
        label=y_enc_va,
        feature_name=feature_names,
        free_raw_data=False,
        reference=tr_set,
    )
    booster = lgb.train(
        params,
        tr_set,
        num_boost_round=cfg.model.num_boost_round,
        valid_sets=[va_set],
        valid_names=["val"],
        callbacks=[
            lgb.early_stopping(cfg.model.early_stopping_rounds, verbose=False),
            lgb.log_evaluation(0),
        ],
    )
    val_pred = booster.predict(X_va, num_iteration=booster.best_iteration)
    # `booster.predict` returns numpy.ndarray for multiclass; cast for mypy.
    return booster, np.asarray(val_pred, dtype=np.float64)


# ----------------------------------------------------------------
# Metric aggregation
# ----------------------------------------------------------------
def _per_class_prf(y_enc: np.ndarray, y_pred_enc: np.ndarray) -> dict[str, dict[str, float]]:
    """Per-class precision/recall/F1, keyed by signed class label (-1/0/+1)."""
    p, r, f, _ = precision_recall_fscore_support(
        y_enc,
        y_pred_enc,
        labels=list(range(len(_CLASSES))),
        zero_division=0.0,
    )
    out: dict[str, dict[str, float]] = {}
    for i, c in enumerate(_CLASSES):
        out[str(c)] = {
            "precision": float(p[i]),
            "recall": float(r[i]),
            "f1": float(f[i]),
        }
    return out


def _multiclass_auc(y_enc: np.ndarray, proba: np.ndarray) -> float:
    """One-vs-rest macro-averaged ROC AUC. Returns NaN if only one class is present."""
    if len(np.unique(y_enc)) < 2:
        return float("nan")
    try:
        score = roc_auc_score(
            y_enc,
            proba,
            multi_class="ovr",
            average="macro",
            labels=list(range(len(_CLASSES))),
        )
        return float(score)
    except ValueError:
        # Raised when a fold's truth has fewer than 2 classes after purging.
        return float("nan")


# ----------------------------------------------------------------
# Main entry point
# ----------------------------------------------------------------
def train(cfg: TrainConfig) -> dict[str, Any]:
    """
    Run the full training pipeline. Returns the in-memory report and writes
    the artifact bundle to `<output_dir>/<name>/`.
    """
    log.info("ml.train starting: %s", cfg.name)

    prices = _load_ohlcv_csv(cfg.data.prices_csv)
    prices = prices.filter((pl.col("date") >= cfg.data.start_date) & (pl.col("date") <= cfg.data.end_date))
    if prices.is_empty():
        raise RuntimeError(f"no rows in {cfg.data.prices_csv} for {cfg.data.start_date}→{cfg.data.end_date}")
    prices = _select_symbols(prices, cfg.data.max_symbols, cfg.data.symbol_seed)

    X, y, sample_end_idx, meta, feature_names = _build_dataset(prices, cfg)
    log.info(
        "dataset: %d samples × %d features, %d symbols, label dist %s",
        X.shape[0],
        X.shape[1],
        meta["symbol"].n_unique(),
        {int(c): int((y == c).sum()) for c in _CLASSES},
    )

    y_enc = np.asarray([_CLASS_TO_IDX[int(v)] for v in y.tolist()], dtype=np.int32)

    cv = PurgedKFold(cfg.cv.n_splits, sample_end_idx, embargo_frac=cfg.cv.embargo_frac)

    mlflow.set_tracking_uri(settings.mlflow_tracking_uri)
    mlflow.set_experiment(cfg.mlflow_experiment or settings.mlflow_experiment_name)

    # OOF prediction container — NaN for samples never in any val fold (none,
    # by PurgedKFold's contract, but we initialize defensively).
    oof_proba = np.full((X.shape[0], len(_CLASSES)), np.nan, dtype=np.float64)
    fold_metrics: list[dict[str, Any]] = []
    feature_importance_gain: np.ndarray | None = None

    with mlflow.start_run(run_name=cfg.name) as run:
        run_id: str = run.info.run_id

        # Log hyperparameters + dataset shape upfront so any subsequent crash
        # still leaves a debuggable run on the tracking server.
        mlflow.log_params(
            {
                "n_samples": X.shape[0],
                "n_features": X.shape[1],
                "n_symbols": meta["symbol"].n_unique(),
                "feature_set_version": FEATURE_SET_VERSION,
                "n_splits": cfg.cv.n_splits,
                "embargo_frac": cfg.cv.embargo_frac,
                "label_horizon": cfg.label.horizon,
                "label_pt_sigma": cfg.label.pt_sigma,
                "label_sl_sigma": cfg.label.sl_sigma,
                "label_vol_window": cfg.label.vol_window,
                "num_boost_round": cfg.model.num_boost_round,
                "early_stopping_rounds": cfg.model.early_stopping_rounds,
                **{f"lgb_{k}": v for k, v in cfg.model.params.items()},
            }
        )

        for fold, (tr_idx, va_idx) in enumerate(cv.split(X)):
            if tr_idx.size == 0 or va_idx.size == 0:
                log.warning("fold %d empty after purging — skipping", fold)
                continue

            booster, val_proba = _train_one_fold(
                X[tr_idx],
                y_enc[tr_idx],
                X[va_idx],
                y_enc[va_idx],
                feature_names=feature_names,
                cfg=cfg,
            )
            oof_proba[va_idx] = val_proba

            val_pred_enc = np.argmax(val_proba, axis=1)
            fold_logloss = float(log_loss(y_enc[va_idx], val_proba, labels=list(range(len(_CLASSES)))))
            fold_bal_acc = float(balanced_accuracy_score(y_enc[va_idx], val_pred_enc))
            fold_auc = _multiclass_auc(y_enc[va_idx], val_proba)

            fold_metrics.append(
                {
                    "fold": fold,
                    "train_size": int(tr_idx.size),
                    "val_size": int(va_idx.size),
                    "best_iteration": int(booster.best_iteration or 0),
                    "val_logloss": fold_logloss,
                    "val_balanced_accuracy": fold_bal_acc,
                    "val_macro_auc_ovr": fold_auc,
                }
            )
            mlflow.log_metrics(
                {
                    f"fold{fold}_val_logloss": fold_logloss,
                    f"fold{fold}_val_balanced_accuracy": fold_bal_acc,
                    f"fold{fold}_val_macro_auc_ovr": (fold_auc if not np.isnan(fold_auc) else 0.0),
                }
            )

            # Accumulate gain-importance across folds — same feature ordering
            # by construction since lgb.Dataset was built with feature_names.
            gain = booster.feature_importance(importance_type="gain").astype(np.float64)
            feature_importance_gain = (
                gain if feature_importance_gain is None else feature_importance_gain + gain
            )

        if not fold_metrics:
            raise RuntimeError("no folds produced predictions")

        # ---------- aggregated OOF metrics ----------
        oof_mask = ~np.isnan(oof_proba[:, 0])
        oof_y_enc = y_enc[oof_mask]
        oof_p = oof_proba[oof_mask]
        oof_pred_enc = np.argmax(oof_p, axis=1)

        agg: dict[str, Any] = {
            "oof_logloss": float(log_loss(oof_y_enc, oof_p, labels=list(range(len(_CLASSES))))),
            "oof_balanced_accuracy": float(balanced_accuracy_score(oof_y_enc, oof_pred_enc)),
            "oof_macro_auc_ovr": _multiclass_auc(oof_y_enc, oof_p),
            "per_class": _per_class_prf(oof_y_enc, oof_pred_enc),
        }

        mlflow.log_metrics(
            {
                "oof_logloss": agg["oof_logloss"],
                "oof_balanced_accuracy": agg["oof_balanced_accuracy"],
                "oof_macro_auc_ovr": (
                    agg["oof_macro_auc_ovr"] if not np.isnan(agg["oof_macro_auc_ovr"]) else 0.0
                ),
                "cv_logloss_mean": float(np.mean([m["val_logloss"] for m in fold_metrics])),
                "cv_balanced_accuracy_mean": float(
                    np.mean([m["val_balanced_accuracy"] for m in fold_metrics])
                ),
            }
        )
        for cls_label, scores in agg["per_class"].items():
            for k, v in scores.items():
                mlflow.log_metric(f"oof_class{cls_label}_{k}", float(v))

        # ---------- assemble report + write artifacts ----------
        report: dict[str, Any] = {
            "name": cfg.name,
            "mlflow_run_id": run_id,
            "dataset": {
                "n_samples": int(X.shape[0]),
                "n_features": int(X.shape[1]),
                "n_symbols": int(meta["symbol"].n_unique()),
                "feature_set_version": FEATURE_SET_VERSION,
                "label_distribution": {int(c): int((y == c).sum()) for c in _CLASSES},
                "date_range": {
                    "min": str(meta["date"].min()),
                    "max": str(meta["date"].max()),
                },
            },
            "cv": {"n_splits": cfg.cv.n_splits, "embargo_frac": cfg.cv.embargo_frac},
            "fold_metrics": fold_metrics,
            "oof_metrics": agg,
        }

        artifact_paths = _write_artifacts(
            cfg=cfg,
            meta=meta,
            oof_proba=oof_proba,
            oof_mask=oof_mask,
            feature_names=feature_names,
            feature_importance_gain=feature_importance_gain,
            report=report,
        )
        report["artifacts"] = artifact_paths

        # Log the artifact directory so the MLflow UI links straight to it.
        mlflow.log_artifacts(artifact_paths["dir"], artifact_path="bundle")

    log.info("ml.train done: %s (run_id=%s)", cfg.name, run_id)
    return report


# ----------------------------------------------------------------
# Artifact bundle
# ----------------------------------------------------------------
def _write_artifacts(
    *,
    cfg: TrainConfig,
    meta: pl.DataFrame,
    oof_proba: np.ndarray,
    oof_mask: np.ndarray,
    feature_names: list[str],
    feature_importance_gain: np.ndarray | None,
    report: dict[str, Any],
) -> dict[str, str]:
    out_dir = Path(cfg.output_dir) / cfg.name
    out_dir.mkdir(parents=True, exist_ok=True)

    # ---------- OOF predictions CSV ----------
    # `prob_-1`, `prob_0`, `prob_+1` columns + the picked class. NaNs (samples
    # never in a val fold) are written as nulls so a downstream join doesn't
    # silently treat them as zero.
    oof_df = meta.with_columns(
        pl.Series("prob_neg1", oof_proba[:, 0]),
        pl.Series("prob_zero", oof_proba[:, 1]),
        pl.Series("prob_pos1", oof_proba[:, 2]),
        pl.Series("in_oof", oof_mask),
    )
    pred_class = np.full(oof_proba.shape[0], np.nan, dtype=np.float64)
    pred_class[oof_mask] = np.array(
        [_CLASSES[i] for i in np.argmax(oof_proba[oof_mask], axis=1)],
        dtype=np.float64,
    )
    oof_df = oof_df.with_columns(pl.Series("pred_class", pred_class))
    oof_df.write_csv(out_dir / "oof_predictions.csv")

    # ---------- feature importances ----------
    if feature_importance_gain is not None:
        fi_df = pl.DataFrame(
            {
                "feature": feature_names,
                "gain_total": feature_importance_gain.tolist(),
            }
        ).sort("gain_total", descending=True)
        fi_df.write_csv(out_dir / "feature_importances.csv")

    # ---------- training report ----------
    (out_dir / "train_report.json").write_text(json.dumps(report, indent=2, default=str), encoding="utf-8")

    # ---------- reproducibility manifest ----------
    # Same hashing scheme as the backtest runner: sha256 over sorted
    # (date, symbol, adj_close) tuples. Reuse — no fork, single source of
    # truth across backtest + ml planes.
    prices = _load_ohlcv_csv(cfg.data.prices_csv).filter(
        (pl.col("date") >= cfg.data.start_date) & (pl.col("date") <= cfg.data.end_date)
    )
    prices = _select_symbols(prices, cfg.data.max_symbols, cfg.data.symbol_seed)
    data_tuples: list[tuple[Any, ...]] = [
        (r["date"].isoformat(), r["symbol"], float(r["adj_close"])) for r in prices.iter_rows(named=True)
    ]
    manifest = build_manifest(config=config_to_dict(cfg), data_tuples=data_tuples)
    (out_dir / "manifest.json").write_text(manifest.to_json(), encoding="utf-8")

    # ---------- config snapshot ----------
    (out_dir / "config.snapshot.json").write_text(
        json.dumps(config_to_dict(cfg), indent=2, default=str), encoding="utf-8"
    )

    return {
        "dir": str(out_dir),
        "train_report": str(out_dir / "train_report.json"),
        "oof_predictions": str(out_dir / "oof_predictions.csv"),
        "feature_importances": str(out_dir / "feature_importances.csv"),
        "manifest": str(out_dir / "manifest.json"),
        "config_snapshot": str(out_dir / "config.snapshot.json"),
    }


# Re-exported for quick interactive use.
def manifest_dict_for_cfg(cfg: TrainConfig) -> dict[str, Any]:
    """Build the manifest as a dict for tests/reports without writing it."""
    prices = _load_ohlcv_csv(cfg.data.prices_csv).filter(
        (pl.col("date") >= cfg.data.start_date) & (pl.col("date") <= cfg.data.end_date)
    )
    prices = _select_symbols(prices, cfg.data.max_symbols, cfg.data.symbol_seed)
    data_tuples: list[tuple[Any, ...]] = [
        (r["date"].isoformat(), r["symbol"], float(r["adj_close"])) for r in prices.iter_rows(named=True)
    ]
    manifest = build_manifest(config=config_to_dict(cfg), data_tuples=data_tuples)
    return asdict(manifest)


__all__ = ["manifest_dict_for_cfg", "train"]
